// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTlF4eHbiSQLrthzhvGwoiCIeucLLQg0g',
    appId: '1:1044491487797:web:1cfe7b08892205aa48bf7c',
    messagingSenderId: '1044491487797',
    projectId: 'culero-407005',
    authDomain: 'culero-407005.firebaseapp.com',
    storageBucket: 'culero-407005.appspot.com',
    measurementId: 'G-HPS844SGDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC65FPTKwDVIzxy-BYK3kGl-20EpRV4OsA',
    appId: '1:1044491487797:android:787e9a2d5cc39a0b48bf7c',
    messagingSenderId: '1044491487797',
    projectId: 'culero-407005',
    storageBucket: 'culero-407005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8RcQstsZyXtxTZMX-8PKhkHUm65LDHdY',
    appId: '1:1044491487797:ios:2cf970b0e3dd97c348bf7c',
    messagingSenderId: '1044491487797',
    projectId: 'culero-407005',
    storageBucket: 'culero-407005.appspot.com',
    iosBundleId: 'com.culero.app',
  );
}
